#!/usr/bin/env php
<?php
/**
 * 
 * Wrapper script for the pear command.
 * 
 * You can set your own configuration values for pear in
 * `$system/config/pear.config.php`. These values are then added to the pear
 * command with `-d $key=$val`.
 * 
 * @author Antti Holvikari <anttih@gmail.com>
 * 
 * @author Paul M. Jones <pmjones@solarphp.com>
 * 
 */

// path to Solar-system
$system = dirname(dirname(__FILE__));

// path to PEAR source files in the system
$pear_dir = "$system/source/pear";

// the serialized file of pear-user config values
$serial_user = "$pear_dir/etc/user";

// the serialized file of pear-system config values
$serial_system = "$pear_dir/etc/system";

// default config values
$default = array(
    'auto_discover'     => 0,
    'bin_dir'           => "$pear_dir/bin",
    'cache_dir'         => "$system/tmp/pear/cache",
    'cache_ttl'         => 3600,
    'cfg_dir'           => "$pear_dir/cfg",
    'data_dir'          => "$pear_dir/data",
    'default_channel'   => "pear.php.net",
    'doc_dir'           => "$pear_dir/doc",
    'download_dir'      => "$system/tmp/pear/download",
    'ext_dir'           => null,
    'http_proxy'        => null,
    'master_server'     => "pear.php.net",
    'password'          => null,
    'php_bin'           => null,
    'php_dir'           => "$pear_dir/php",
    'php_ini'           => null,
    'preferred_mirror'  => "pear.php.net",
    'preferred_state'   => "stable",
    'remote_config'     => null,
    'sig_bin'           => null,
    'sig_keydir'        => "$pear_dir/etc/keys",
    'sig_keyid'         => null,
    'sig_type'          => "gpg",
    'temp_dir'          => "$system/tmp/pear",
    'test_dir'          => "$pear_dir/test",
    'umask'             => 22,
    'username'          => null,
    'verbose'           => null,
    'www_dir'           => "$system/docroot",
);

// read user configuration from file, and merge with default
$config = include "$system/config/pear.config.php";
$config = array_merge($default, $config);

// create command-line options for the serialized config files
$opts = array(
    "-C $serial_system",
    "-c $serial_user",
);

// create command-line options for the config values
foreach ($config as $key => $val) {
    // only create options for non-null non-false values
    if ($val !== false && $val !== null) {
        $val = escapeshellarg($val);
        $opts[] = "-d $key=$val";
    }
}

// take off "./script/pear" and retain command arguments
array_shift($argv);
$args = implode(' ', $argv);

// use the specialized pearsolar "binary" if it's available.
// otherwise, use `env` to find the system-wide standard pear "binary".
$pear_bin = "{$config['bin_dir']}/pearsolar";
if (! file_exists($pear_bin) || ! is_readable($pear_bin)) {
    $pear_bin = '/usr/bin/env pear';
}

// build the command on separate lines, in case we need to echo it
$cmd = "$pear_bin \\\n    "
     . implode(" \\\n    ", $opts) . " \\\n    "
     . $args;

// if we are being more than just a little verbose,
// echo the command before executing
if ($config['verbose'] > 1) {
    echo "$cmd\n\n";
}

// run command
passthru($cmd, $exit_code);

// done!
exit($exit_code);
